name: PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-
      - name: Install dependencies
        run: |
          python -m pip install -U poetry twine
          poetry config virtualenvs.in-project true
          poetry install
      - name: Build package
        run: poetry build
      - name: Upload to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_NON_INTERACTIVE: true
